import { SetupPlan } from '@/lib/types'

const now = new Date().toISOString()

export const DEFAULT_PLANS: Omit<SetupPlan, 'userId'>[] = [
  {
    id: 'plan_breakout',
    name: 'Breakout',
    description: 'Momentum breakout from key levels with volume confirmation.',
    isDefault: true,
    criteria: [
      {
        id: 'htf_context',
        label: 'HTF context aligned',
        description: 'Higher timeframe trend and structure support the direction',
        weight: 25,
        validator: { type: 'has_market_condition' },
      },
      {
        id: 'liquidity_zone',
        label: 'Liquidity zone identified',
        description: 'Key liquidity zone or level of interest noted in the trade',
        weight: 20,
        validator: { type: 'has_notes' },
      },
      {
        id: 'entry_trigger',
        label: 'Entry trigger respected',
        description: 'A valid entry trigger was used (strategy/playbook)',
        weight: 25,
        validator: { type: 'has_strategy' },
      },
      {
        id: 'rr_ratio',
        label: 'Minimum RR 1:2 respected',
        description: 'Risk-to-reward ratio is at least 1:2',
        weight: 15,
        validator: { type: 'min_rr', value: 2 },
      },
      {
        id: 'journalized',
        label: 'Trade journalized with notes',
        description: 'Trade has written notes documenting context and reasoning',
        weight: 15,
        validator: { type: 'has_notes' },
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plan_retracement',
    name: 'Retracement',
    description: 'Pullback entry on trend continuation at key Fibonacci or structure levels.',
    isDefault: true,
    criteria: [
      {
        id: 'htf_trend',
        label: 'HTF trend confirmed',
        description: 'Higher timeframe trend direction documented in market condition',
        weight: 20,
        validator: { type: 'has_market_condition' },
      },
      {
        id: 'level_identified',
        label: 'Fibonacci or structure level',
        description: 'Entry linked to a playbook with defined levels',
        weight: 20,
        validator: { type: 'has_playbook' },
      },
      {
        id: 'entry_candle',
        label: 'Entry candle / trigger signal',
        description: 'Stop loss placed at invalidation level',
        weight: 25,
        validator: { type: 'has_sl' },
      },
      {
        id: 'rr_retracement',
        label: 'Minimum RR 1:2.5',
        description: 'Risk-to-reward ratio is at least 1:2.5',
        weight: 20,
        validator: { type: 'min_rr', value: 2.5 },
      },
      {
        id: 'journalized',
        label: 'Trade journalized',
        description: 'Trade documented with notes',
        weight: 15,
        validator: { type: 'has_notes' },
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plan_reversal',
    name: 'Reversal',
    description: 'Counter-trend entry at key structural reversal zones.',
    isDefault: true,
    criteria: [
      {
        id: 'structure_break',
        label: 'Structure break confirmed',
        description: 'Market condition documents the structural shift',
        weight: 25,
        validator: { type: 'has_market_condition' },
      },
      {
        id: 'key_level',
        label: 'Key support/resistance level',
        description: 'Strategy identifies the key reversal level',
        weight: 25,
        validator: { type: 'has_strategy' },
      },
      {
        id: 'sl_placed',
        label: 'Stop loss placed beyond structure',
        description: 'Stop loss is defined beyond the invalidation level',
        weight: 20,
        validator: { type: 'has_sl' },
      },
      {
        id: 'tp_defined',
        label: 'Take profit at next structure',
        description: 'Take profit is defined at a logical target',
        weight: 15,
        validator: { type: 'has_tp' },
      },
      {
        id: 'journalized',
        label: 'Trade journalized with notes',
        description: 'Trade has written notes',
        weight: 15,
        validator: { type: 'has_notes' },
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plan_ict',
    name: 'ICT',
    description: 'Inner Circle Trader methodology — PD arrays, killzones, market structure.',
    isDefault: true,
    criteria: [
      {
        id: 'pd_array',
        label: 'PD array identified',
        description: 'Premium/discount array identified via strategy',
        weight: 25,
        validator: { type: 'has_strategy' },
      },
      {
        id: 'killzone',
        label: 'Killzone entry',
        description: 'Entry taken during London/NY killzone session',
        weight: 20,
        validator: { type: 'has_session' },
      },
      {
        id: 'market_structure',
        label: 'Market structure shift confirmed',
        description: 'Market condition documents the MSS/BOS',
        weight: 25,
        validator: { type: 'has_market_condition' },
      },
      {
        id: 'rr_ict',
        label: 'Minimum RR 1:3',
        description: 'ICT setups require minimum 1:3 reward',
        weight: 15,
        validator: { type: 'min_rr', value: 3 },
      },
      {
        id: 'journalized',
        label: 'Journalized with context',
        description: 'Detailed notes on the trade context',
        weight: 15,
        validator: { type: 'has_notes' },
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plan_smc',
    name: 'SMC',
    description: 'Smart Money Concepts — order blocks, BOS/CHOCH, liquidity sweeps.',
    isDefault: true,
    criteria: [
      {
        id: 'order_block',
        label: 'Order block identified',
        description: 'Order block identified and linked to strategy',
        weight: 25,
        validator: { type: 'has_strategy' },
      },
      {
        id: 'bos_choch',
        label: 'BOS/CHOCH confirmed',
        description: 'Break of structure or CHOCH documented in market condition',
        weight: 25,
        validator: { type: 'has_market_condition' },
      },
      {
        id: 'liquidity_grab',
        label: 'Liquidity grab present',
        description: 'Liquidity sweep or grab noted in trade notes',
        weight: 20,
        validator: { type: 'has_notes' },
      },
      {
        id: 'sl_below_ob',
        label: 'SL placed beyond OB',
        description: 'Stop loss placed beyond the order block invalidation',
        weight: 15,
        validator: { type: 'has_sl' },
      },
      {
        id: 'tp_pov',
        label: 'TP at POI/opposing OB',
        description: 'Take profit defined at a point of interest',
        weight: 15,
        validator: { type: 'has_tp' },
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
]
